insert into testdbyasin.User(id, CREATE_DATE, name, UPDATE_DATE, password) values (1, NOW(), 'abbas', NOW(), '123')
insert into testdbyasin.User(id, CREATE_DATE, name, UPDATE_DATE, password) values (2, NOW(), 'yasin', NOW(), 'tlmn')
insert into testdbyasin.User(id, CREATE_DATE, name, UPDATE_DATE, password) values (3, NOW(), 'trbzn', NOW(), 'spr')
insert into testdbyasin.User(id, CREATE_DATE, name, UPDATE_DATE, password) values (4, NOW(), 'ayse', NOW(), 'yldrm')
insert into testdbyasin.Roles (id, CREATE_DATE, name, UPDATE_DATE) values (1, NOW(), 'ROLE_USER', NOW())
insert into testdbyasin.Roles (id, CREATE_DATE, name, UPDATE_DATE) values (2, NOW(), 'ROLE_ADMIN', NOW())
insert into testdbyasin.Roles (id, CREATE_DATE, name, UPDATE_DATE) values (3, NOW(), 'ROLE_MANAGER', NOW())
insert into testdbyasin.Roles (id, CREATE_DATE, name, UPDATE_DATE) values (4, NOW(), 'sabuk', NOW())
insert into testdbyasin.UserRoles (id, CREATE_DATE, name, UPDATE_DATE, user_id, role_id) values (1, NOW(), 'ABBUSR', NOW(), 1, 1)
insert into testdbyasin.UserRoles (id, CREATE_DATE, name, UPDATE_DATE, user_id, role_id) values (2, NOW(), 'YASROLE', NOW(), 2, 2)
insert into testdbyasin.UserRoles (id, CREATE_DATE, name, UPDATE_DATE, user_id, role_id) values (3, NOW(), 'TRBZMNGR', NOW(), 3, 3)
insert into testdbyasin.UserRoles (id, CREATE_DATE, name, UPDATE_DATE, user_id, role_id) values (4, NOW(), 'AYSEMNGR', NOW(), 4, 4)
