insert into testdbyasin.User(id, CREATE_DATE, name, UPDATE_DATE, password) values (1, NOW(), 'abbas', NOW(), '123')
insert into testdbyasin.User(id, name, password) values (2, 'yasin', 'tlmn')
insert into testdbyasin.User(id, name, password) values (3, 'trbzn', 'spr')
insert into testdbyasin.User(id, name, password) values (4, 'ayse', 'yldrm')
insert into testdbyasin.ROLES (id, name) values (1, 'ROLE_USER')
insert into testdbyasin.ROLES (id, name) values (2, 'ROLE_ADMIN')
insert into testdbyasin.ROLES (id, name) values (3, 'ROLE_MANAGER')
insert into testdbyasin.ROLES (id, name) values (4, 'sabuk')
insert into testdbyasin.USERROLES (id, name, user_id, role_id) values (1, 'ABBUSR', 1, 1)
insert into testdbyasin.USERROLES (id, name, user_id, role_id) values (2, 'YASROLE', 2, 2)
insert into testdbyasin.USERROLES (id, name, user_id, role_id) values (3, 'TRBZMNGR', 3, 3)
insert into testdbyasin.USERROLES (id, name, user_id, role_id) values (4, 'AYSEMNGR', 4, 4)